### ISSUE TITLE
Anchor link to section ID - pagination issues

### ISSUE THREAD

**Issue by kiaramelissa** [kevinoes/page-slider-js#1]
Hey, great script! Love it!

Just noted some weird behaviour when linking to the slides/sections.

I have created a menu that has anchor links to the section IDs. When clicked it takes the user directly to the correct slide, however the pagination doesn't register correctly and thinks I am on the first slide still. Then wont let me scroll back up. After I scroll down it kind of realises the issue and fixes itself up with a bit of jumping.

Code is exactly as per your original with the exception of restyled and positioned pagination.

As the site isn't live yet, here is a video example to show what I mean.
https://www.dropbox.com/s/247iznci260gaiu/Slider-Issue.mov?dl=0 

Note the pagination on the right hand side

Any help would be so appreciated!

**Comment by kevinoes** [comment]
Hey! Thanks for your feedback :) When clicking the links you've created, are you using basic anchor links? If so, there is a function in the script which you can use instead, `gotoSlide(target-anchor-name)`.

**Comment by kevinoes** [comment]
Hey! Thank you for your feedback!

I've added an update for this just now. Check the updated files :)

Btw, your site looks great 👍

**Comment by kiaramelissa** [comment]
Thank you so much for doing that!! 

And thanks for the compliment :) Cant wait to launch
